# Generated by Django 4.2 on 2023-11-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BotSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("salesperson_name", models.CharField(max_length=255)),
                ("company_name", models.CharField(max_length=255)),
                ("company_business", models.CharField(max_length=255)),
                ("company_values", models.CharField(max_length=255)),
                ("conversation_purpose", models.CharField(max_length=255)),
                ("salesperson_rol", models.CharField(max_length=255)),
                ("conversation_type", models.CharField(max_length=255)),
                ("conversation_stage", models.CharField(max_length=255)),
            ],
        ),
    ]
