# Generated by Django 4.2 on 2023-11-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backbot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botsettings",
            name="company_business",
            field=models.CharField(max_length=1800),
        ),
        migrations.AlterField(
            model_name="botsettings",
            name="company_name",
            field=models.CharField(max_length=1800),
        ),
        migrations.AlterField(
            model_name="botsettings",
            name="company_values",
            field=models.CharField(max_length=1800),
        ),
        migrations.AlterField(
            model_name="botsettings",
            name="conversation_purpose",
            field=models.CharField(max_length=1800),
        ),
        migrations.AlterField(
            model_name="botsettings",
            name="conversation_stage",
            field=models.CharField(max_length=1800),
        ),
        migrations.AlterField(
            model_name="botsettings",
            name="conversation_type",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="botsettings",
            name="salesperson_name",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="botsettings",
            name="salesperson_rol",
            field=models.CharField(max_length=25),
        ),
    ]
