# Generated by Django 4.2 on 2023-11-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backbot", "0002_alter_botsettings_company_business_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botsettings",
            name="company_name",
            field=models.CharField(max_length=50),
        ),
    ]
