# Generated by Django 4.2 on 2023-12-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backbot", "0004_apikey"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="key",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
