# Generated by Django 4.2 on 2023-12-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backbot", "0005_alter_apikey_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="key",
            field=models.CharField(max_length=100),
        ),
    ]
