# Generated by Django 4.2 on 2023-12-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backbot", "0006_alter_apikey_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListadoEtiquetas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor_etiqueta", models.CharField(max_length=50, unique=True)),
                ("observacion", models.CharField(max_length=50)),
                ("color", models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
