# Generated by Django 4.2 on 2023-12-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backbot", "0007_listadoetiquetas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listadoetiquetas",
            name="observacion",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
