# Generated by Django 4.2 on 2023-12-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backbot", "0008_alter_listadoetiquetas_observacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listadoetiquetas",
            name="color",
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
